import type { FlowProject } from '../types'

export const reportGeneratorDemo: FlowProject = {
  id: 'demo-report-generator',
  name: 'Research Report Generator',
  nodes: [
    {
      id: 'n1',
      type: 'input',
      position: { x: 80, y: 120 },
      data: {
        kind: 'input',
        label: 'Report Topic',
        description: 'The subject to research and report on.',
        prompt: '',
        code: '',
        outputType: 'text',
        noteText: '',
        uiLabel: 'Report topic',
        uiDefaultValue: 'The impact of artificial intelligence on modern software development',
      },
    },
    {
      id: 'n2',
      type: 'llm',
      position: { x: 340, y: 80 },
      data: {
        kind: 'llm',
        label: 'Generate Report Content',
        description: 'LLM writes structured report content including sections, a statistics table, and key findings.',
        prompt: `You are a professional research analyst. Write a detailed report on: {{input}}

Return ONLY a JSON object (no markdown code fences) with this exact structure:
{
  "title": "Report title",
  "executive_summary": "2-3 sentence summary",
  "sections": [
    { "heading": "Section heading", "body": "2-3 paragraph body text" },
    { "heading": "Section heading", "body": "2-3 paragraph body text" },
    { "heading": "Section heading", "body": "2-3 paragraph body text" }
  ],
  "statistics": [
    { "metric": "Metric name", "value": "Value", "source": "Source" },
    { "metric": "Metric name", "value": "Value", "source": "Source" },
    { "metric": "Metric name", "value": "Value", "source": "Source" },
    { "metric": "Metric name", "value": "Value", "source": "Source" }
  ],
  "key_findings": ["Finding 1", "Finding 2", "Finding 3", "Finding 4"],
  "conclusion": "Concluding paragraph"
}`,
        code: '',
        outputType: 'text',
        noteText: '',
        uiLabel: '',
        uiDefaultValue: '',
      },
    },
    {
      id: 'n3',
      type: 'function',
      position: { x: 620, y: 80 },
      data: {
        kind: 'function',
        label: 'Render Report HTML',
        description: 'Transforms the structured JSON into a polished HTML report with styled sections, statistics table, and key findings.',
        prompt: '',
        code: `// Parse the LLM JSON output
let data
try {
  data = JSON.parse(input)
} catch {
  // Strip any accidental markdown fences
  const clean = input.replace(/^\`\`\`[a-z]*\\n?/,'').replace(/\`\`\`$/,'').trim()
  data = JSON.parse(clean)
}

const { title, executive_summary, sections, statistics, key_findings, conclusion } = data

const sectionsHtml = sections.map(s => \`
  <h2>\${s.heading}</h2>
  <p>\${s.body.replace(/\\n/g, '</p><p>')}</p>
\`).join('')

const statsRows = statistics.map(s => \`
  <tr><td>\${s.metric}</td><td><strong>\${s.value}</strong></td><td>\${s.source}</td></tr>
\`).join('')

const findingsHtml = key_findings.map(f => \`<li>\${f}</li>\`).join('')

const html = \`
<div style="max-width:760px;margin:0 auto;font-family:Georgia,serif;color:#1a1a1a;line-height:1.7;">
  <h1 style="font-family:'Helvetica Neue',sans-serif;font-size:2em;border-bottom:3px solid #2a4a7f;padding-bottom:0.4em;color:#2a4a7f;">\${title}</h1>

  <div style="background:#f0f4ff;border-left:4px solid #5b8ff9;padding:1em 1.4em;margin:1.5em 0;border-radius:0 6px 6px 0;">
    <strong style="font-family:sans-serif;font-size:0.85em;letter-spacing:0.08em;color:#2a4a7f;">EXECUTIVE SUMMARY</strong>
    <p style="margin:0.5em 0 0;">\${executive_summary}</p>
  </div>

  \${sectionsHtml}

  <h2 style="font-family:'Helvetica Neue',sans-serif;color:#2a4a7f;margin-top:2em;">Key Statistics</h2>
  <table style="border-collapse:collapse;width:100%;margin:1em 0;">
    <thead>
      <tr style="background:#2a4a7f;color:white;">
        <th style="padding:8px 12px;text-align:left;">Metric</th>
        <th style="padding:8px 12px;text-align:left;">Value</th>
        <th style="padding:8px 12px;text-align:left;">Source</th>
      </tr>
    </thead>
    <tbody>
      \${statsRows}
    </tbody>
  </table>

  <h2 style="font-family:'Helvetica Neue',sans-serif;color:#2a4a7f;margin-top:2em;">Key Findings</h2>
  <ul style="padding-left:1.5em;">\${findingsHtml}</ul>

  <h2 style="font-family:'Helvetica Neue',sans-serif;color:#2a4a7f;margin-top:2em;">Conclusion</h2>
  <p>\${conclusion}</p>

  <p style="margin-top:3em;font-size:0.8em;color:#888;border-top:1px solid #ddd;padding-top:1em;">
    Generated by PromptFlow · \${new Date().toLocaleDateString('en-GB', { day:'numeric', month:'long', year:'numeric' })}
  </p>
</div>
\`

return { __html: html }`,
        outputType: 'html',
        noteText: '',
        uiLabel: '',
        uiDefaultValue: '',
      },
    },
    {
      id: 'n4',
      type: 'output',
      position: { x: 900, y: 120 },
      data: {
        kind: 'output',
        label: 'Report Output',
        description: 'Displays the rendered HTML report. Use the HTML or PDF export buttons to save a sharable document.',
        prompt: '',
        code: '',
        outputType: 'html',
        noteText: '',
        uiLabel: '',
        uiDefaultValue: '',
      },
    },
    {
      id: 'n5',
      type: 'note',
      position: { x: 80, y: 290 },
      data: {
        kind: 'note',
        label: 'Note',
        description: '',
        prompt: '',
        code: '',
        outputType: 'text',
        noteText: '📄 After running, use the **HTML** or **PDF** buttons in the output panel to save a sharable report.',
        uiLabel: '',
        uiDefaultValue: '',
      },
    },
  ],
  edges: [
    { id: 'e1-2', source: 'n1', target: 'n2', type: 'gradient', animated: true },
    { id: 'e2-3', source: 'n2', target: 'n3', type: 'gradient', animated: true },
    { id: 'e3-4', source: 'n3', target: 'n4', type: 'gradient', animated: true },
  ],
}
